spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
logging:
  file: logs/application.log
  level:
    root: debug